apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: default
subjects:
- kind: ServiceAccount
  name: kubernetes-client-inside-pod-sa 
  namespace: default
roleRef:
  kind: Role 
  name: pod-list-only
  apiGroup: rbac.authorization.k8s.io
